### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by metulburr** [iminurnamez/pyroller#109]
I get a KeyError from using cli args from what i believe is from the last few commits as it worked updated yesterday. 

the args i am using are: (and error)

    metulburr@ubuntu ~/repos/pyroller $ python3 pyroller.py -c -S CRAPS -d
    Loading chipmunk for Linux (64bit) [/home/metulburr/repos/pyroller/pymunk/libchipmunk64.so]
    Traceback (most recent call last):
      File "pyroller.py", line 8, in <module>
        main()
      File "/home/metulburr/repos/pyroller/data/main.py", line 25, in main
        "TITLESCREEN" : title_screen.TitleScreen(),
      File "/home/metulburr/repos/pyroller/data/states/title_screen.py", line 51, in __init__
        self.check_straight_arg()
      File "/home/metulburr/repos/pyroller/data/states/title_screen.py", line 69, in check_straight_arg
        self.persist["casino_player"] = CasinoPlayer(self.stats)
      File "/home/metulburr/repos/pyroller/data/components/casino_player.py", line 53, in __init__
        self.stats[game][stat] = stats[game][stat]
    KeyError: 'Video Poker'
    metulburr@ubuntu ~/repos/pyroller  $ python pyroller.py -c -S CRAPS -d
    Loading chipmunk for Linux (64bit) [/home/metulburr/repos/pyroller/pymunk/libchipmunk64.so]
    Traceback (most recent call last):
      File "pyroller.py", line 8, in <module>
        main()
      File "/home/metulburr/repos/pyroller/data/main.py", line 25, in main
        "TITLESCREEN" : title_screen.TitleScreen(),
      File "/home/metulburr/repos/pyroller/data/states/title_screen.py", line 51, in __init__
        self.check_straight_arg()
      File "/home/metulburr/repos/pyroller/data/states/title_screen.py", line 69, in check_straight_arg
        self.persist["casino_player"] = CasinoPlayer(self.stats)
      File "/home/metulburr/repos/pyroller/data/components/casino_player.py", line 53, in __init__
        self.stats[game][stat] = stats[game][stat]
    KeyError: 'Video Poker'

EDIT:
found it is the result of only the -S option

**Comment by Mekire** [comment]
Your json file is just out of date.  Easiest fix is to delete it and let it get rebuilt.  Video poker and pachinko have now been added to the stats screen.  when you use the -S flag the game uses load game, rather than new game.

**Comment by metulburr** [comment]
oh ok. I forgot about that.
