### ISSUE TITLE
Baccarat: unorderable types get_nearest_sprite

### ISSUE THREAD

**Issue by Mekire** [iminurnamez/pyroller#147]
@bitcraft 
A py3 issue arises with `get_nearest_sprite`

Shown below:
```python
Traceback (most recent call last):
  File "pyroller.py", line 8, in <module>
    main()
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\main.py", line 46, in main
    run_it.main()
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\tools.py", line 145, in main
    self.event_loop()
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\tools.py", line 103, in event_loop
    self.state.get_event(event, self.scale)
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\states\baccarat\table.py", line 246, in get_event
    self.player_chips.get_event(event, scale)
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\states\baccarat\chips.py", line 174, in get_event
    self.handle_pointer(tools.scaled_mouse_pos(scale))
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\states\baccarat\chips.py", line 213, in handle_pointer
    closest_sprite = self.snap_sprite(pos)
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\states\baccarat\chips.py", line 274, in snap_sprite
    nearest_sprites = self.get_nearest_sprites(pos, distance)
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\states\baccarat\chips.py", line 309, in get_nearest_sprites
    l.sort()
TypeError: unorderable types: Chip() < Chip()
```

**Comment by bitcraft** [comment]
Thanks for the info.  I guess I ought to just test everything on py3 from now on.  I have a fix, for it, but I'll send a PR after I have tested it.
