### ISSUE TITLE
Pachinko broken: empty() method

### ISSUE THREAD

**Issue by Mekire** [iminurnamez/pyroller#169]
@bitcraft 
Minor error causing crash with Pachinko after last merge.

```python
Traceback (most recent call last):
  File "pyroller.py", line 8, in <module>
    main()
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\main.py", line 50, in main
    run_it.main()
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\tools.py", line 146, in main
    self.update(time_delta)
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\tools.py", line 59, in update
    self.state.update(self.render_surf,self.keys,self.now,dt,self.scale)
  File "C:\Python27\Lib\Python modules\repos\Mine\pyrollers\mine_pyroller\data\states\pachinko\pachinko.py", line 198, in update
    self.hud.empty(surface, self._clear_surface)
TypeError: empty() takes exactly 1 argument (3 given)
```

**Comment by bitcraft** [comment]
fixed
