### ISSUE TITLE
Blackjack: Crashes since update. chip_total_label.

### ISSUE THREAD

**Issue by Mekire** [iminurnamez/pyroller#47]
Issue with `self.chip_total_label` being undefined.  Simple to fix.

```
Traceback (most recent call last):
  File "C:\Python27\Lib\Python modules\Mine\pyroller\pyroller.py", line 8, in <module>
    main()
  File "C:\Python27\Lib\Python modules\Mine\pyroller\data\main.py", line 39, in main
    run_it.main()
  File "C:\Python27\Lib\Python modules\Mine\pyroller\data\tools.py", line 126, in main
    self.update(time_delta)
  File "C:\Python27\Lib\Python modules\Mine\pyroller\data\tools.py", line 55, in update
    self.state.update(self.render_surf,self.keys,self.now,dt,self.scale)
  File "C:\Python27\Lib\Python modules\Mine\pyroller\data\states\blackjack\blackjack.py", line 404, in update
    self.draw(surface, dt)
  File "C:\Python27\Lib\Python modules\Mine\pyroller\data\states\blackjack\blackjack.py", line 433, in draw
    self.chip_total_label.draw(surface)
AttributeError: 'Blackjack' object has no attribute 'chip_total_label'
```

-Mek

**Comment by iminurnamez** [comment]
It's from self.elapsed being less than 17 on the first frame. Should be fixed now.
