### ISSUE TITLE
KeyError: 'bingo-menu-bar'

### ISSUE THREAD

**Issue by metulburr** [iminurnamez/pyroller#61]
error after [this pull request](https://github.com/iminurnamez/pyroller/commit/0121b7c1579d7b9cb197fc4c1c799e9d8ca48b65)
```
metulburr@ubuntu ~/repos/pyroller  $ python pyroller.py -c
Loading chipmunk for Linux (64bit) [/usr/local/lib/python2.7/dist-packages/pymunk/libchipmunk64.so]
[    80] ::   DEBUG                Bingo :: Adding new executor initialise, 140712936755472
[    82] ::   DEBUG                Bingo :: Adding new executor potential-winners, 140712936342608
Traceback (most recent call last):
  File "pyroller.py", line 8, in <module>
    main()
  File "/home/metulburr/repos/pyroller/data/main.py", line 30, in main
    "BINGO"       : bingo.Bingo(),
  File "/home/metulburr/repos/pyroller/data/states/bingo/main.py", line 68, in __init__
    super(Bingo, self).__init__(states.S_INITIALISE)
  File "/home/metulburr/repos/pyroller/data/states/bingo/statemachine.py", line 88, in __init__
    self.initUI()
  File "/home/metulburr/repos/pyroller/data/states/bingo/main.py", line 191, in initUI
    'bingo-menu-bar', S['menu-bar-position'], scale=S['menu-bar-scale']
  File "/home/metulburr/repos/pyroller/data/components/common.py", line 135, in __init__
    self.sprite = prepare.GFX[filename if filename else name]
KeyError: 'bingo-menu-bar'
metulburr@ubuntu ~/repos/pyroller  $ 

```

**Comment by Mekire** [comment]
Fixed.
